name: Publish Python distributions to PyPI

on:
  push:
    tags:
     - '*'

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python
      run: uv python install 3.13
    - name: Build
      run: |
        version=$(echo $GITHUB_REF | cut -d / -f 3)
        sed -i "s/__version__ = .*/__version__ = \"$version\"/g" mmuxer/__init__.py
        uv build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
